#Header
pages_list:
  #blog : '/_posts'
  #about: '/about'
  #research: '/research'
  publications: '/publications'
  cv: '/cv'
  #materials: '/materials'
  #archive: '/archive'
  #feed: '/atom.xml'
  #categories: '/categories'

# Setup
title: Carsten Bundt
tagline: Signal over Noise
url: https://carstenbundt.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - _posts

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: 'category/:name/'
#    year: archive/year
#    month: archive/month
#    tag: archive/tag
#    category: archive/category
#  permalinks:
#    year: '/:year/'
#    month: '/:year/:month/'
#    tag: '/tags/:name/'
#    category: '/category/:name/'

sass:
  sass_dir: _sass
  style: :compressed

# Options

# GA measurement ID
google_analytics: G-J9R798XE1M

# Specify the author for blog posts
author:
  name: Carsten
  #url: https://twitter.com/mdo
  email: bundt.carsten@gmail.com

# Custom vars
version: 3.0.0
